	
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 14-Sep-2016 13:58:04

% Create figure
figure1 = figure;
colormap('gray');

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.102857142857143 0.0840630472854641 0.793650793650794 0.875656742556918]);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.5 500.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 500.5]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'Layer','top','TickDir','out','XTick',...
    [0 250 500],'XTickLabel',{'-1','0','1'});
